#!/bin/sh

# for some reason Arquillian requires this jar, even though it's probably never used.

# The version number of 'jdk' is crude, but, running this does seem to solve the dependency problem.

mvn install:install-file -Dfile=/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/jconsole.jar -DgroupId=sun.jdk -DartifactId=jconsole -Dversion=jdk -Dpackaging=jar
