= CJP-Examples: files for _Checking Java Programs_

I've been an advocate of advanced techniques and strong testing for most of my life as a software developer.
This repository was first set up in 2007 (in CVS; moved to GitHub in 2015).
It was originally built with Ant but has mostly been moved to Maven to simplify classpath.
Classpath is also the reason I chose to split this repo into
*multiple projects*, each an Eclipse project and a Maven-buildable project.
Otherwise the classpath (and the Maven pom file) would become overly large.

This repo has been used for:

* The 2007 book Checking Java Programs;
* The 2015 Video Series.
* The 2022 book Checking Java Programs.

Not everything builds or runs at the moment: patches welcome; complaints, not so much.
A few parts of this will indeed likely stay on Ant because
one or two of the tools are only available as Ant plugins.
While I do know about the maven-ant-plugin, it's still just easier this way.

There are several main directories:

. _general_ is the catch-all containing various demos
. _spock_ contains the Spock examples;
. _junit4_ contains JUnit 4 examples
. _junit5_ contains JUnit 5 examples
. _pmd_ contains some examples of PMD
. _spotbugs_ contains some examples of SpotBugs, the follow-on project to FindBugs
. _jpf_ - not yet updated, contains Java PathFinder examples

== JPF: Java PathFinder

JavaPathFinder (JPF) is a really nice set of tools for examine state modelling of your Java code.
It was created at NASA to verify the software used in the Mars Rover control program 
(not the embedded software in the device, but the ground-based controller software).
Unfortunately, it has never been easy to get started with, nor has it made the leap from
Ant to Maven.
JPF seemed for a while like _abandonware_, but has been revived and is being modernized
and even expanded.

== Attention Users of the 2007 Book Version

The head commit of the master branch  will be totally wrong for you if you try to follow
the directions in the 2007 edition of the book. If you still want to follow a
decade-old book you should only have to do `git checkout a1ad04` after cloning the git repo.

When you install that version YOU WILL HAVE TO SET some Eclipse variables
before it will work! This is expected. Emails asking why it doesn't
work out of the box when you haven't read this file are probably going
to be ignored, but you won't know that if you didn't read
this file; that's why it's called a README file, I suppose.
The details are in the 2007 book.

== Contact

Thanks for reading/watching my book and/or my video series.

Ian Darwin

http://cjp.darwinsys.com/[Book website]

http://shop.oreilly.com/product/0636920042723.do[Java Testing for Developers], videocast Learning Path

http://shop.oreilly.com/product/9780596510237.do[Order the 2007 book from O'Reilly]
